Feature/review react query
supercoding-commerce/FE pull request #222
Opened 2023-10-24 14:49 UTC by cho-subin

close #ISSUE_NUMBER

## 💡 개요

## 📝 작업 내용

## ‼️ 주의 사항

## 🔗 참고자료

2023-10-24 17:55 UTC, moonjieun commented
확인했습니다 쿼리 적용 국🖐✨approve 해놨어용

2023-10-24 17:56 UTC, moonjieun approved these changes

2023-10-25 02:25 UTC, KIMSEUNGGYU reviewed
오 react-query 굿굿굿 입니다!! 
리뷰 확인 부탁드립니다

2023-10-25 02:25 UTC, KIMSEUNGGYU commented on src/components/Detail/detailReview/Review.tsx
>    /** filterOrderList() : 이미 작성했던 오더리스트 제외 필터링 */
reaect-query 에 reviewList 로 봤는데 따로 상태로 관리하는 이유가 있을까요?

2023-10-25 02:25 UTC, KIMSEUNGGYU commented on src/components/Detail/detailReview/ReviewWrite.tsx
> +        alert('리뷰 추가 성공111');
111 은 빼도 될듯합니다.

2023-10-25 02:25 UTC, KIMSEUNGGYU commented on src/pages/DetailPage/DetailPage.tsx
> +              // isReview={isReview}
주석 제거!

2023-10-25 02:25 UTC, KIMSEUNGGYU commented on src/queries/review/mutation.ts
> +      console.log('업데이트');
로그도 제거 부탁드립니다

2023-10-25 02:25 UTC, KIMSEUNGGYU commented on src/queries/review/query.ts
굿굿굿!!

2023-10-25 02:25 UTC, KIMSEUNGGYU commented on src/queries/review/mutation.ts
굿굿굿!

2023-10-25 02:29 UTC, KIMSEUNGGYU requested changes
리뷰 확인 후 변경 바랍니다

2023-10-25 08:02 UTC, cho-subin commented on src/components/Detail/detailReview/Review.tsx
>    /** filterOrderList() : 이미 작성했던 오더리스트 제외 필터링 */
React query의 reviewList를 가지고 최신순, 별점순 정렬을 위해 따로 상태관리를 했습니다ㅠㅇㅠ..

2023-10-29 13:11 UTC, KIMSEUNGGYU approved these changes

2023-10-29 13:56 UTC, KIMSEUNGGYU requested changes
리뷰 남겼습니다! 
react-query 는 이제 마스터하셨네요@

2023-10-29 13:56 UTC, KIMSEUNGGYU commented on src/apis/review.ts
> +export const postReview = async (payload: FormData): Promise<DetailReview> => {
`Promise<DetailReview> =` 여게이서  `> =` 오타 있는거 같아요

2023-10-29 13:56 UTC, KIMSEUNGGYU commented on src/components/Detail/detailReview/Review.tsx
> +  // };
필요없으면 지워도 될거 같아요

2023-10-29 13:56 UTC, KIMSEUNGGYU commented on src/components/Detail/detailReview/Review.tsx
> +      {reviewList?.map((item, idx) => {
98번 라인에서 reviewList 없는거 체크해서 reviewList?. 에서 `?.` 옵션널 제거해도 좋을거 같아요

2023-10-29 13:56 UTC, KIMSEUNGGYU commented on src/components/Detail/detailReview/ReviewBox.tsx
> +  // handleDeleteReview: (deleteReview: number) => void;
주석..

2023-10-29 13:58 UTC, KIMSEUNGGYU commented on src/apis/review.ts
> +export const postReview = async (payload: FormData): Promise<DetailReview> => {
아니군요 ㅋㅋㅋㅋ 화살표 함수구나 ㅋㅋ

2023-10-29 14:05 UTC, KIMSEUNGGYU approved these changes
LGTM 👍👍

2023-10-29 14:05 UTC, merged