Feature/category productpage
supercoding-commerce/FE pull request #225
Opened 2023-10-26 17:21 UTC by moonjieun

close #224 

## 💡 개요

## 📝 작업 내용
- useInfiniteQuery 설치
- pageRef 와 useState를 이용하여 상품데이터 보관한것을 useInfiniteQuery 적용하여  로딩과 에러처리,페이지당데이터를 편리하게 관리
-  useInfiniteQuery  import 부분 tanstack으로 변경 ( react-query로 import시 에러발생 수정 )

## ‼️ 주의 사항

## 🔗 참고자료

2023-10-27 06:53 UTC, YukDDong approved these changes
확인했습니다!

2023-10-27 10:21 UTC, KIMSEUNGGYU requested changes
나머지는 다 좋습니다!

사용하지 않는 라이브러리 삭제 부탁합니다!

2023-10-27 10:21 UTC, KIMSEUNGGYU commented on package.json
> +    "react-query-infinite-scroll": "^1.0.4",
해당 라이브러리 사용하지 않는거 같습니다! 
제거 부탁드립니다!

2023-10-28 09:06 UTC, moonjieun commented on package.json
> +    "react-query-infinite-scroll": "^1.0.4",
넵 감사합니다 😁

2023-10-28 09:21 UTC, moonjieun commented on package.json
> +    "react-query-infinite-scroll": "^1.0.4",
확인부탁드립니다+ 제거하였습니다

2023-10-28 12:17 UTC, KIMSEUNGGYU approved these changes

2023-10-28 13:43 UTC, merged